platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: capi-k8s-release-ci
  - name: capi-k8s-release
  - name: component-repo

outputs:
  - name: vendir-bumped-capi-k8s-release

run:
  path: capi-k8s-release-ci/ci/tasks/bump-vendir/task.sh
