---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-dind

inputs:
  - name: capi-k8s-release-ci
  - name: source-repository

outputs:
  - name: image

params:
  CONTEXT_PATH: null
  ADDITIONAL_ARGS: null

run:
  path: capi-k8s-release-ci/ci/tasks/build-with-pack.sh
