---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
- name: capi-k8s-release-ci
- name: capi-k8s-release
- name: capi-docker-image
- name: cf-api-controllers-docker-image
- name: registry-buddy-docker-image
- name: nginx-docker-image
- name: backup-metadata-generator-docker-image
- name: statsd-exporter-docker-image
- name: cloud-controller-ng
- name: capi-nginx
- name: cf-api-controllers
- name: registry-buddy

outputs:
- name: updated-capi-k8s-release

params:
  GIT_COMMIT_EMAIL: cf-release-integration@pivotal.io
  GIT_COMMIT_USERNAME: "relint-ci"

run:
  path: capi-k8s-release-ci/ci/tasks/bump-capi-k8s-release-image-refs.sh
