
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: go-units

inputs:
  - name: cf-api-controllers
  - name: capi-k8s-release-ci

params: {}

run:
  path: capi-k8s-release-ci/ci/tasks/run-cf-api-controllers-unit-tests.sh
