
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: registry-buddy
  - name: capi-k8s-release-ci

params:
  REGISTRY_BASE_PATH:
  REGISTRY_PASSWORD:
  REGISTRY_USERNAME:

run:
  path: capi-k8s-release-ci/ci/tasks/run-registry-buddy-integration-tests.sh
