---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: ruby-units

inputs:
  - name: cloud_controller_ng
  - name: capi-k8s-release-ci

run:
  path: capi-k8s-release-ci/ci/tasks/run_cc_unit_tests.sh

params:
  DB: ~
  RUN_IN_PARALLEL: ~
